<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About | Supernatural Character Gallery</title>
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=UnifrakturCook:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/styles.css">
</head>

<body>

    <!-- Navigation Bar -->

    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="details.html">Details</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="new-character-form.html">Add a Character</a></li>
        </ul>
    </nav>

    <!-- Main Content -->
     <main>
        <h1>About this Gallery</h1>

        <h3>
            Learn more about this collection of <em>Supernatural</em> characters.
        </h3>

        <img class="about-image" src="Images/supernatural-banner.gif" alt="Supernatural Television Series">
        
        <section class="about-content">
            <h2>Welcome to the Supernatural Character Gallery</h2>
            <p>
                This gallery was created as an educational project for a software engineering course. 
                It serves as a showcase of my favorite characters from the hit television show 
                <em>Supernatural</em>, allowing fans to explore and learn more about them.
            </p>

            <h2>Data & Attribution</h2>
            <p>
                <em>Supernatural</em> and all related characters are the property Warner Bros. Entertainment. Character
                information is based on events from the television series. Images are used solely for educational purposes
                as part of a Software Engineering course project.
            </p>

        </section>

    </main>

    <!-- Footer -->
    <footer>
        <p>&copy; 2026 Supernatural Character Gallery. Created as an educational project.</p>
        <p>Supernatural and all related characters are property of their respective owners.</p>
    </footer>

</body>
</html>